
# This file is used to configure pre-commit hooks.
# See https://pre-commit.com for more information
default_stages: [pre-commit, pre-push]

default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
        name: Check JSON files
        description: Attempts to load all json files to verify syntax.
        exclude: .vscode/settings.json
      - id: check-yaml
        name: Check YAML files
        description: Attempts to load all yaml files to verify syntax.
      - id: check-toml
        name: Check TOML files
        description: Attempts to load all TOML files to verify syntax.
      - id: detect-private-key
        name: Private key detection
        description: Checks for the existence of private keys.
      - id: end-of-file-fixer
        name: End of files have newlines
        description: Makes sure files end in a newline and only a newline.
      - id: check-docstring-first
        name: Check docstrings come first
        description: Checks for a common error of placing code before the docstring.
      - id: mixed-line-ending
        name: Mixed line endings
        description: Replaces or checks mixed line ending (like mix of LF and CRLF).
      - id: trailing-whitespace
        name: Trailing whitespaces
        description: Trims trailing whitespaces.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
    -   id: ruff
        name: Ruff linter on codebase
        description: An extremely fast Python linter and code formatter, written in Rust.
        args: [--fix, --config=ruff.toml, --exclude=tests]
    -   id: ruff-format
        name: Ruff formatter on codebase
        args: [--config=ruff.toml, --exclude=tests]
    -   id: ruff
        name: Ruff linter on tests
        args: [--fix-only, --config=ruff.toml]
    -   id: ruff-format
        name: Ruff rormatter on tests
        args: [--config=ruff.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: MyPy
        description: MyPy is an optional static type checker for Python.
        args: [--explicit-package-bases, --disallow-untyped-defs, --disallow-incomplete-defs, --disallow-untyped-calls]
        # If setting up a project with multiple component/src/ directories
        # then set this to true to pass all filenames to mypy
        #pass_filenames: false
        types: [python]
        # Additional dependencies required for the hook
        # (will be installed in a separate python environment purely for this hook)
        # here you should add typing dependencies to help mypy do appropriate type checking
        # otherwise imported types are typed as typing.Any
        additional_dependencies:
          - pytest==8.0.1
          # Other common examples:
          # - "types-PyYAML"
          # - "types-redis"
          # - types-python-dateutil
          # - pandas-stubs
