# Configures Ruff, the Python linter and formatter.

# Exclude a variety of commonly ignored directories.
extend-exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    ".decontainer",
    ".github",
    ".mypy_cache",
    ".ruff_cache",
    "artifacts",
    "data",
    "docs",
]

# Assume python3.11.
target-version = "py311"

# Same as Black.
line-length = 110
indent-width = 4

[lint]
# https://docs.astral.sh/ruff/rules/
select = [
    "F", # Pyflakes
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "D", # pydocstyle doc
    "I", # isort
    "N", # PEP8 naming
    "S", # flake8-bandit
    "PL", # Pylint
    "FLY", # flynt static-join-to-f-string
    # "UP", # pyupgrade
    ]
ignore = [
    "S101", # S101 Use of `assert` detected
    "PLR2004", # PLR2004 Magic value used in comparison (eg. if value == 2)
]

# Allow fix for all enabled rules (when `--fix` / fix = true) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.pydocstyle]
convention = "google"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings.
# This is currently disabled by default, but it is planned for this to be opt-out in the future.
docstring-code-format = false
# Set the line length limit used when formatting code snippets in docstrings.
# This only has an effect when the `docstring-code-format` setting is enabled.
docstring-code-line-length = "dynamic"

# 4. Ignore in all `__init__.py` files, and in selected subdirectories.
[lint.per-file-ignores]
"__init__.py" = [
    "E402", # import violations
    "D104", # Missing docstring in public package
    "F401", # Unused import
]
"**/{tests,docs,tools}/*" = [
    "D" # Ignore docstring errors in tests, docs, and tools directories.
]
